name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'
      env:
        FILE: /.index.html
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
  final:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name:  Deploy static site to S3 bucket
      run: aws s3 sync ./index.html s3://gitlab-website001-staging
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
